# Generated by Django 3.1.6 on 2021-02-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_user_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="protected_child_name",
        ),
        migrations.RemoveField(
            model_name="application",
            name="protected_party_name",
        ),
        migrations.RemoveField(
            model_name="application",
            name="respondent_name",
        ),
        migrations.AddField(
            model_name="application",
            name="date_of_will",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="deceased_date_of_death",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="deceased_name",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
