# Generated by Django 4.0.7 on 2024-02-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_idir_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
