# Generated by Django 3.1.7 on 2021-11-23 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20211123_0944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="user_name",
        ),
        migrations.RemoveField(
            model_name="application",
            name="user_type",
        ),
    ]
