# Generated by Django 3.1.7 on 2021-11-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auto_20211123_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="preparedpdf",
            name="json_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
