# Generated by Django 4.0.3 on 2022-04-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_surveyresult_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedpdf',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
